### ISSUE TITLE
Rect native couldn't find preset "es2015" relative to the directory 

### ISSUE THREAD

**Issue by akaiz** [solinor/paymenthighway-javascript-lib#11]
I am trying to use this lib in a react native app but every time I require or import,  I do get this error message.
 TransformError :/Users/xx/Appname/node_modules/paymenthighway/js/index.js: couldn't find preset "es2015" relative to the directory "/Users/xx/Appname/node_modules/paymenthighway"

**Comment by Kostersson** [comment]
es2015 babel settings are removed in https://github.com/solinor/paymenthighway-javascript-lib/pull/12 . Will be published in next patch [2.0.1](https://github.com/solinor/paymenthighway-javascript-lib/commit/f5286570ea6b868d6c7b274579d820310dd597c0).
